apiVersion: apps/v1
kind: Deployment
metadata:
  name: hinco-wedding-frontend
  labels:
    app: hinco-wedding-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hinco-wedding-frontend
  template:
    metadata:
      labels:
        app: hinco-wedding-frontend
    spec:
      imagePullSecrets:
        - name: github-image-pull
      containers:
        - name: hinco-wedding-frontend
          image: ghcr.io/hinco114/hinco-wedding:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hinco-wedding-frontend
  labels:
    app: hinco-wedding-frontend
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: hinco-wedding-frontend
  type: NodePort
