# Reference : https://github.com/eksctl-io/eksctl/tree/main/examples

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: WINC-eks
  region: ap-northeast-2
  tags:
    karpenter.sh/discovery: WINC-eks

iam:
  withOIDC: true # required (for Karpenter)
karpenter:
  version: 'v0.20.0' # Exact version must be specified

vpc:
  cidr: 10.20.0.0/16
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
  nat:
    gateway: Single # other options: Disable, Single (default)

cloudWatch:
  clusterLogging:
    # enable specific types of cluster control plane logs
    enableTypes: ["audit", "authenticator", "controllerManager"]
    # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
    # supported special values: "*" and "all"

    # Sets the number of days to retain the logs for (see [CloudWatch docs](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutRetentionPolicy.html#API_PutRetentionPolicy_RequestSyntax)).
    # By default, log data is stored in CloudWatch Logs indefinitely.
    logRetentionInDays: 60

managedNodeGroups:
  - name: managed-ng-1
    instanceSelector:
      vCPUs: 2
      memory: "4" # 4 GiB, unit defaults to GiB
    spot: true
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
    volumeSize: 80
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
    privateNetworking: true
