apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - storageclass.yaml
  - pv.yaml

configMapGenerator:
  - name: nfs-config
    envs:
      - nfs_config.env

patches:
  - target:
      kind: PersistentVolumeClaim
    patch: |-
      - op: add
        path: /spec/storageClassName
        value: nas-nfs


# Apply nfs config to storageclass and pv using replacements
replacements:
  - source:
      kind: ConfigMap
      name: nfs-config
      fieldPath: data.SERVER
    targets:
      - select:
          kind: PersistentVolume
          name: mongodb-persistent-volume
        fieldPaths:
          - spec.nfs.server
      - select:
          kind: StorageClass
          name: nas-nfs
        fieldPaths:
          - parameters.server
  - source:
      kind: ConfigMap
      name: nfs-config
      fieldPath: data.PATH
    targets:
      - select:
          kind: PersistentVolume
          name: mongodb-persistent-volume
        fieldPaths:
          - spec.nfs.path
      - select:
          kind: StorageClass
          name: nas-nfs
        fieldPaths:
          - parameters.path
