apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-persistent-volume
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  nfs:
    server: {IP_ADDRESS_OF_NFS_SERVER}
    path: {PATH_TO_MONGODB_DATA}
    readOnly: false
  storageClassName: nas-nfs
