apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nas-nfs
provisioner: hinco-nas-nfs
parameters:
  server: {AUTO_ADDED_BY_KUSTOMIZE}
  path: {AUTO_ADDED_BY_KUSTOMIZE}
  readOnly: "false"
